--SELECT title, length FROM film WHERE title LIKE '%n' ORDER BY length DESC LIMIT 5;
--SELECT title, length FROM film WHERE title LIKE '%n' ORDER BY length ASC offset 5 LIMIT 10 ;
--SELECT first_name, last_name FROM customer WHERE store_id = 1 ORDER BY last_name DESC LIMIT 4;
